/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author Thiago
 */
public class TelaPrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuRepublica = new javax.swing.JMenu();
        jMenuItemManterRepublica = new javax.swing.JMenuItem();
        jMenuItemManterMoradores = new javax.swing.JMenuItem();
        jMenuItemConfirmarSolucoes = new javax.swing.JMenuItem();
        jMenuItemConvidarAceitarConvites = new javax.swing.JMenuItem();
        jMenuItemCriarRepublica = new javax.swing.JMenuItem();
        jMenuItemBuscarVagas = new javax.swing.JMenuItem();
        jMenuItemConsultarResultadoMensal = new javax.swing.JMenuItem();
        jMenuItemManterReclamacoesSugestoes = new javax.swing.JMenuItem();
        jMenuMorador = new javax.swing.JMenu();
        jMenuItemManterPerfil = new javax.swing.JMenuItem();
        jMenuItemAceitarConvite = new javax.swing.JMenuItem();
        jMenuTarefas = new javax.swing.JMenu();
        jMenuItemManterTarefas = new javax.swing.JMenuItem();
        jMenuItemRegistrarConclusao = new javax.swing.JMenuItem();
        jMenulancamentos = new javax.swing.JMenu();
        jMenuItemManterReceitaDespesa = new javax.swing.JMenuItem();
        jMenuItemFazerEstornoLancamento = new javax.swing.JMenuItem();
        jMenuItemConsultarMinhasReceitasDespesas = new javax.swing.JMenuItem();
        jMenuItemRegistrarPagamentoReceitaDespesa = new javax.swing.JMenuItem();
        jMenuOpcoes = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestão de Repúblicas");

        jMenuRepublica.setText("República");

        jMenuItemManterRepublica.setText("Manter República");
        jMenuRepublica.add(jMenuItemManterRepublica);

        jMenuItemManterMoradores.setText("ManterMoradores");
        jMenuRepublica.add(jMenuItemManterMoradores);

        jMenuItemConfirmarSolucoes.setText("Confirmar Soluções");
        jMenuRepublica.add(jMenuItemConfirmarSolucoes);

        jMenuItemConvidarAceitarConvites.setText("Convidar/Aceitar Convites");
        jMenuRepublica.add(jMenuItemConvidarAceitarConvites);

        jMenuItemCriarRepublica.setText("Criar República");
        jMenuRepublica.add(jMenuItemCriarRepublica);

        jMenuItemBuscarVagas.setText("Buscar Vagas");
        jMenuRepublica.add(jMenuItemBuscarVagas);

        jMenuItemConsultarResultadoMensal.setText("Consultar Resultado Mensal");
        jMenuRepublica.add(jMenuItemConsultarResultadoMensal);

        jMenuItemManterReclamacoesSugestoes.setText("Manter Reclamações/Sugestões");
        jMenuRepublica.add(jMenuItemManterReclamacoesSugestoes);

        jMenuBar1.add(jMenuRepublica);

        jMenuMorador.setText("Morador");

        jMenuItemManterPerfil.setText("ManterPerfil");
        jMenuMorador.add(jMenuItemManterPerfil);

        jMenuItemAceitarConvite.setText("AceitarConvite");
        jMenuMorador.add(jMenuItemAceitarConvite);

        jMenuBar1.add(jMenuMorador);

        jMenuTarefas.setText("Tarefas");

        jMenuItemManterTarefas.setText("ManterTarefas");
        jMenuTarefas.add(jMenuItemManterTarefas);

        jMenuItemRegistrarConclusao.setText("Registrar Conclusão ");
        jMenuTarefas.add(jMenuItemRegistrarConclusao);

        jMenuBar1.add(jMenuTarefas);

        jMenulancamentos.setText("Lançamentos");

        jMenuItemManterReceitaDespesa.setText("Manter receitas e despesas");
        jMenulancamentos.add(jMenuItemManterReceitaDespesa);

        jMenuItemFazerEstornoLancamento.setText("Fazer estorno de lançamentos");
        jMenulancamentos.add(jMenuItemFazerEstornoLancamento);

        jMenuItemConsultarMinhasReceitasDespesas.setText("Consultar minhas receitas e despesas");
        jMenulancamentos.add(jMenuItemConsultarMinhasReceitasDespesas);

        jMenuItemRegistrarPagamentoReceitaDespesa.setText("Registrar pagamento de receita ou despesa");
        jMenulancamentos.add(jMenuItemRegistrarPagamentoReceitaDespesa);

        jMenuBar1.add(jMenulancamentos);

        jMenuOpcoes.setText("Opções");

        jMenuItemSair.setText("Sair");
        jMenuOpcoes.add(jMenuItemSair);

        jMenuBar1.add(jMenuOpcoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    

    public JMenuItem getjMenuItemConsultarMinhasReceitasDespesas() {
        return jMenuItemConsultarMinhasReceitasDespesas;
    }

    public JMenuItem getjMenuItemFazerEstornoLancamento() {
        return jMenuItemFazerEstornoLancamento;
    }

    public JMenuItem getjMenuItemManterReceitaDespesa() {
        return jMenuItemManterReceitaDespesa;
    }

    /**
     * @param args the command line arguments
     */
    public JMenuItem getjMenuItemRegistrarPagamentoReceitaDespesa() {
        return jMenuItemRegistrarPagamentoReceitaDespesa;
    }

    public JMenuItem getjMenuItemAceitarConvite() {
        return jMenuItemAceitarConvite;
    }

    public JMenuItem getjMenuItemBuscarVagas() {
        return jMenuItemBuscarVagas;
    }

    public JMenuItem getjMenuItemConfirmarSolucoes() {
        return jMenuItemConfirmarSolucoes;
    }

    public JMenuItem getjMenuItemConsultarResultadoMensal() {
        return jMenuItemConsultarResultadoMensal;
    }

    public JMenuItem getjMenuItemConvidarAceitarConvites() {
        return jMenuItemConvidarAceitarConvites;
    }

    public JMenuItem getjMenuItemCriarRepublica() {
        return jMenuItemCriarRepublica;
    }

    public JMenuItem getjMenuItemManterMoradores() {
        return jMenuItemManterMoradores;
    }

    public JMenuItem getjMenuItemManterPerfil() {
        return jMenuItemManterPerfil;
    }

    public JMenuItem getjMenuItemManterReclamacoesSugestoes() {
        return jMenuItemManterReclamacoesSugestoes;
    }

    public JMenuItem getjMenuItemManterRepublica() {
        return jMenuItemManterRepublica;
    }

    public JMenuItem getjMenuItemManterTarefas() {
        return jMenuItemManterTarefas;
    }

    public JMenuItem getjMenuItemRegistrarConclusao() {
        return jMenuItemRegistrarConclusao;
    }

    public JMenuItem getjMenuItemSair() {
        return jMenuItemSair;
    }

    public JMenu getjMenuMorador() {
        return jMenuMorador;
    }

    public JMenu getjMenuOpcoes() {
        return jMenuOpcoes;
    }

    public JMenu getjMenuRepublica() {
        return jMenuRepublica;
    }

    public JMenu getjMenuTarefas() {
        return jMenuTarefas;
    }

    /**
     * @param args the command line arguments
     */
    public JMenu getjMenulancamentos() {
        return jMenulancamentos;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAceitarConvite;
    private javax.swing.JMenuItem jMenuItemBuscarVagas;
    private javax.swing.JMenuItem jMenuItemConfirmarSolucoes;
    private javax.swing.JMenuItem jMenuItemConsultarMinhasReceitasDespesas;
    private javax.swing.JMenuItem jMenuItemConsultarResultadoMensal;
    private javax.swing.JMenuItem jMenuItemConvidarAceitarConvites;
    private javax.swing.JMenuItem jMenuItemCriarRepublica;
    private javax.swing.JMenuItem jMenuItemFazerEstornoLancamento;
    private javax.swing.JMenuItem jMenuItemManterMoradores;
    private javax.swing.JMenuItem jMenuItemManterPerfil;
    private javax.swing.JMenuItem jMenuItemManterReceitaDespesa;
    private javax.swing.JMenuItem jMenuItemManterReclamacoesSugestoes;
    private javax.swing.JMenuItem jMenuItemManterRepublica;
    private javax.swing.JMenuItem jMenuItemManterTarefas;
    private javax.swing.JMenuItem jMenuItemRegistrarConclusao;
    private javax.swing.JMenuItem jMenuItemRegistrarPagamentoReceitaDespesa;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuMorador;
    private javax.swing.JMenu jMenuOpcoes;
    private javax.swing.JMenu jMenuRepublica;
    private javax.swing.JMenu jMenuTarefas;
    private javax.swing.JMenu jMenulancamentos;
    // End of variables declaration//GEN-END:variables
}
